version: '3.3'

services:
    
    minio:
        image: minio/minio
        environment:
            MINIO_ACCESS_KEY: root
            MINIO_SECRET_KEY: super_secret_key
        volumes:
          - minio-data:/export
        ports:
          - "9001:9000"
        command: server /data

    server:
        build:
            dockerfile: ./Dockerfile
            context: .
        volumes:
            - .:/app
        ports:
            - 8000:8000

        depends_on:
            - minio
            - mongo
        command: npm run dev

    mongo:
        image: mongo:3.6.21

volumes:
    minio-data:
    source-code:
